namespace PropertySheetPage
{
    [default_interface]
    runtimeclass AdvancedPage : Microsoft.UI.Xaml.Controls.UserControl, PropertySheetWinUI.IWinUIPropSheetPage
    {
        AdvancedPage();
    }
}
