namespace PropertySheetPage
{
    [default_interface]
	runtimeclass GeneralPage : Microsoft.UI.Xaml.Controls.UserControl, PropertySheetWinUI.IWinUIPropSheetPage
    {
        GeneralPage();
    }
}
