// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_MUICInternalContentExternalBackdropLink_H
#define WINRT_MUICInternalContentExternalBackdropLink_H
#include "winrt/base.h"
#include "winrt/impl/Microsoft.UI.Composition.1.h"
#include "winrt/impl/Microsoft.UI.Composition.2.h"
#include "winrt/impl/Microsoft.UI.Dispatching.2.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include <roapi.h>

#pragma once
WINRT_EXPORT namespace winrt::Microsoft::UI::Composition
{
    enum class CompositionBorderMode : int32_t;
    struct Compositor;
    struct Visual;
}
WINRT_EXPORT namespace winrt::Microsoft::UI::Dispatching
{
    struct DispatcherQueue;
}
WINRT_EXPORT namespace winrt::MUCInternal
{
    struct IContentExternalBackdropLink;
    struct IContentExternalBackdropLinkStatics;
    struct ContentExternalBackdropLink;
}
namespace winrt::impl
{
    template <> struct category<winrt::MUCInternal::IContentExternalBackdropLink> { using type = interface_category; };
    template <> struct category<winrt::MUCInternal::IContentExternalBackdropLinkStatics> { using type = interface_category; };
    template <> struct category<winrt::MUCInternal::ContentExternalBackdropLink> { using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::MUCInternal::ContentExternalBackdropLink> = L"MUCInternal.ContentExternalBackdropLink";
    template <> inline constexpr auto& name_v<winrt::MUCInternal::IContentExternalBackdropLink> = L"MUCInternal.IContentExternalBackdropLink";
    template <> inline constexpr auto& name_v<winrt::MUCInternal::IContentExternalBackdropLinkStatics> = L"MUCInternal.IContentExternalBackdropLinkStatics";
    template <> inline constexpr guid guid_v<winrt::MUCInternal::IContentExternalBackdropLink>{ 0x1054BF83, 0xB35B, 0x5FDE, { 0x8D,0xD7,0xAC,0x3B,0xB3,0xE6,0xCE,0x27 } }; // 1054BF83-B35B-5FDE-8DD7-AC3BB3E6CE27
    template <> inline constexpr guid guid_v<winrt::MUCInternal::IContentExternalBackdropLinkStatics>{ 0x46CAC6FB, 0xBB51, 0x510A, { 0x95,0x8D,0xE0,0xEB,0x41,0x60,0xF6,0x78 } }; // 46CAC6FB-BB51-510A-958D-E0EB4160F678
    template <> struct default_interface<winrt::MUCInternal::ContentExternalBackdropLink> { using type = winrt::MUCInternal::IContentExternalBackdropLink; };
    template <> struct abi<winrt::MUCInternal::IContentExternalBackdropLink>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_DispatcherQueue(void**) noexcept = 0;
            virtual int32_t __stdcall get_ExternalBackdropBorderMode(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_ExternalBackdropBorderMode(int32_t) noexcept = 0;
            virtual int32_t __stdcall get_PlacementVisual(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::MUCInternal::IContentExternalBackdropLinkStatics>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall Create(void*, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_MUCInternal_IContentExternalBackdropLink
    {
        [[nodiscard]] auto DispatcherQueue() const;
        [[nodiscard]] auto ExternalBackdropBorderMode() const;
        auto ExternalBackdropBorderMode(winrt::Microsoft::UI::Composition::CompositionBorderMode const& value) const;
        [[nodiscard]] auto PlacementVisual() const;
    };
    template <> struct consume<winrt::MUCInternal::IContentExternalBackdropLink>
    {
        template <typename D> using type = consume_MUCInternal_IContentExternalBackdropLink<D>;
    };
    template <typename D>
    struct consume_MUCInternal_IContentExternalBackdropLinkStatics
    {
        auto Create(winrt::Microsoft::UI::Composition::Compositor const& compositor) const;
    };
    template <> struct consume<winrt::MUCInternal::IContentExternalBackdropLinkStatics>
    {
        template <typename D> using type = consume_MUCInternal_IContentExternalBackdropLinkStatics<D>;
    };
}

WINRT_EXPORT namespace winrt::MUCInternal
{
    struct WINRT_IMPL_EMPTY_BASES IContentExternalBackdropLink :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IContentExternalBackdropLink>
    {
        IContentExternalBackdropLink(std::nullptr_t = nullptr) noexcept {}
        IContentExternalBackdropLink(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IContentExternalBackdropLinkStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IContentExternalBackdropLinkStatics>
    {
        IContentExternalBackdropLinkStatics(std::nullptr_t = nullptr) noexcept {}
        IContentExternalBackdropLinkStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}

WINRT_EXPORT namespace winrt::MUCInternal
{
    struct WINRT_IMPL_EMPTY_BASES ContentExternalBackdropLink : winrt::MUCInternal::IContentExternalBackdropLink,
        impl::require<ContentExternalBackdropLink, winrt::Windows::Foundation::IClosable, winrt::Microsoft::UI::Composition::ICompositionSupportsSystemBackdrop>
    {
        ContentExternalBackdropLink(std::nullptr_t) noexcept {}
        ContentExternalBackdropLink(void* ptr, take_ownership_from_abi_t) noexcept : winrt::MUCInternal::IContentExternalBackdropLink(ptr, take_ownership_from_abi) {}
        static winrt::MUCInternal::ContentExternalBackdropLink Create(winrt::Microsoft::UI::Composition::Compositor const& compositor);
    };
}

namespace winrt::impl
{
    template <typename D> auto consume_MUCInternal_IContentExternalBackdropLink<D>::DispatcherQueue() const
    {
        void* value{};
        if constexpr (!std::is_same_v<D, winrt::MUCInternal::IContentExternalBackdropLink>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::MUCInternal::IContentExternalBackdropLink, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**) & _winrt_casted_result;
            check_hresult(_winrt_abi_type->get_DispatcherQueue(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**)this;
            check_hresult(_winrt_abi_type->get_DispatcherQueue(&value));
        }
        return winrt::Microsoft::UI::Dispatching::DispatcherQueue{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_MUCInternal_IContentExternalBackdropLink<D>::ExternalBackdropBorderMode() const
    {
        winrt::Microsoft::UI::Composition::CompositionBorderMode value{};
        if constexpr (!std::is_same_v<D, winrt::MUCInternal::IContentExternalBackdropLink>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::MUCInternal::IContentExternalBackdropLink, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**) & _winrt_casted_result;
            check_hresult(_winrt_abi_type->get_ExternalBackdropBorderMode(reinterpret_cast<int32_t*>(&value)));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**)this;
            check_hresult(_winrt_abi_type->get_ExternalBackdropBorderMode(reinterpret_cast<int32_t*>(&value)));
        }
        return value;
    }
    template <typename D> auto consume_MUCInternal_IContentExternalBackdropLink<D>::ExternalBackdropBorderMode(winrt::Microsoft::UI::Composition::CompositionBorderMode const& value) const
    {
        if constexpr (!std::is_same_v<D, winrt::MUCInternal::IContentExternalBackdropLink>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::MUCInternal::IContentExternalBackdropLink, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**) & _winrt_casted_result;
            check_hresult(_winrt_abi_type->put_ExternalBackdropBorderMode(static_cast<int32_t>(value)));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**)this;
            check_hresult(_winrt_abi_type->put_ExternalBackdropBorderMode(static_cast<int32_t>(value)));
        }
    }
    template <typename D> auto consume_MUCInternal_IContentExternalBackdropLink<D>::PlacementVisual() const
    {
        void* value{};
        if constexpr (!std::is_same_v<D, winrt::MUCInternal::IContentExternalBackdropLink>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::MUCInternal::IContentExternalBackdropLink, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**) & _winrt_casted_result;
            check_hresult(_winrt_abi_type->get_PlacementVisual(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLink>**)this;
            check_hresult(_winrt_abi_type->get_PlacementVisual(&value));
        }
        return winrt::Microsoft::UI::Composition::Visual{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_MUCInternal_IContentExternalBackdropLinkStatics<D>::Create(winrt::Microsoft::UI::Composition::Compositor const& compositor) const
    {
        void* result{};
        if constexpr (!std::is_same_v<D, winrt::MUCInternal::IContentExternalBackdropLinkStatics>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::MUCInternal::IContentExternalBackdropLinkStatics, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLinkStatics>**) & _winrt_casted_result;
            check_hresult(_winrt_abi_type->Create(*(void**)(&compositor), &result));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::MUCInternal::IContentExternalBackdropLinkStatics>**)this;
            check_hresult(_winrt_abi_type->Create(*(void**)(&compositor), &result));
        }
        return winrt::MUCInternal::ContentExternalBackdropLink{ result, take_ownership_from_abi };
    }
    template <typename D>
    struct produce<D, winrt::MUCInternal::IContentExternalBackdropLink> : produce_base<D, winrt::MUCInternal::IContentExternalBackdropLink>
    {
        int32_t __stdcall get_DispatcherQueue(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = nullptr;
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_ExternalBackdropBorderMode(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = 0;
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_ExternalBackdropBorderMode(int32_t ) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_PlacementVisual(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = nullptr;
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::MUCInternal::IContentExternalBackdropLinkStatics> : produce_base<D, winrt::MUCInternal::IContentExternalBackdropLinkStatics>
    {
        int32_t __stdcall Create(void* compositor, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::MUCInternal::ContentExternalBackdropLink>(this->shim().Create(*reinterpret_cast<winrt::Microsoft::UI::Composition::Compositor const*>(&compositor)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::MUCInternal
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::MUCInternal::IContentExternalBackdropLink> : winrt::impl::hash_base {};
    template<> struct hash<winrt::MUCInternal::IContentExternalBackdropLinkStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::MUCInternal::ContentExternalBackdropLink> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}

namespace winrt::MUCInternal::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES ContentExternalBackdropLink_base : implements<D, MUCInternal::ContentExternalBackdropLink, I...>
    {
        using base_type = ContentExternalBackdropLink_base;
        using class_type = MUCInternal::ContentExternalBackdropLink;
        using implements_type = typename ContentExternalBackdropLink_base::implements_type;
        using implements_type::implements_type;

        hstring GetRuntimeClassName() const
        {
            return L"MUCInternal.ContentExternalBackdropLink";
        }
    };
}

namespace winrt::MUCInternal::implementation
{
    template <typename D, typename... I>
    using ContentExternalBackdropLinkT = ContentExternalBackdropLink_base<D, I...>;
}


namespace winrt::MUCInternal::implementation
{
    struct ContentExternalBackdropLink : ContentExternalBackdropLinkT<ContentExternalBackdropLink>
    {

        static MUCInternal::ContentExternalBackdropLink Create(winrt::Microsoft::UI::Composition::Compositor compositor)
        {
            winrt::com_ptr<IContentExternalBackdropLinkStatics> factory;
            winrt::hstring activationClass = L"Microsoft.UI.Content.ContentExternalBackdropLink";
            RoGetActivationFactory(static_cast<HSTRING>(winrt::get_abi(activationClass)), winrt::guid_of<IContentExternalBackdropLinkStatics>(), reinterpret_cast<void**>(&factory));
            winrt::MUCInternal::ContentExternalBackdropLink instance{ nullptr };
            factory->Create(winrt::get_abi(compositor), reinterpret_cast<void**>(&instance));
            return instance;
        }
    };
}
namespace winrt::MUCInternal::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES ContentExternalBackdropLinkT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::MUCInternal::IContentExternalBackdropLinkStatics, I...>
    {
        using instance_type = MUCInternal::ContentExternalBackdropLink;

        hstring GetRuntimeClassName() const
        {
            return L"MUCInternal.ContentExternalBackdropLink";
        }
        auto Create(winrt::Microsoft::UI::Composition::Compositor const& compositor)
        {
            return T::Create(compositor);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}
#endif