#include "WinUIPropertySheet.idl"

namespace PropertySheetWinUI
{
    [default_interface]
    runtimeclass PropSheetWindow : Microsoft.UI.Xaml.Window
    {
        PropSheetWindow();
	    void AddPage(IWinUIPropSheetPage page);
		event Windows.Foundation.TypedEventHandler<IInspectable, Microsoft.UI.Xaml.RoutedEventArgs> PropertySheetSave;
    }
}
