#include "WinUIPropertySheet.idl"

namespace PropertySheetWinUI
{
    [default_interface]
    runtimeclass PropSheetWindow : Microsoft.UI.Xaml.Window
    {
        PropSheetWindow();
	    void AddPage(WinUIPropSheetPage page);
    }
}
