namespace PropertySheetWinUI
{
    interface IWinUIPropSheetPage
    {
        void OnSave();
        String GetTitle();
        Microsoft.UI.Xaml.UIElement GetXamlContent();
	}

    [default_interface]
    runtimeclass WinUIPropSheetHeader
    {
        WinUIPropSheetHeader();
	    Boolean IsWizard;
	    String Caption;
        Windows.Foundation.Collections.IVector<IWinUIPropSheetPage> pages;
    }

    [default_interface]
    runtimeclass WinUIPropertySheet
    {
        WinUIPropertySheet();
        void CreatePropertySheet(WinUIPropSheetHeader header);
    }
}
